services:
  - type: web
    name: mmsu-technology-assessment-tool
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_HOST
        fromDatabase:
          name: mmsu-assessment-db
          property: host
      - key: DATABASE_NAME
        fromDatabase:
          name: mmsu-assessment-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: mmsu-assessment-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: mmsu-assessment-db
          property: password
      - key: DATABASE_PORT
        value: 5432

databases:
  - name: mmsu-assessment-db
    databaseName: mmsu_assessments
    user: mmsu_user
    plan: free
